-- 메뉴
CREATE TABLE MENU (
	  ID INT NOT NULL AUTO_INCREMENT 
	, PARENT_NUM INT 
	, DEPTH INT
	, NAME VARCHAR(100) 
	, REG_DATE DATETIME
	, REG_ID VARCHAR(255)
	, UPD_DATE DATETIME
	, UPD_ID VARCHAR(255)
	, PRIMARY KEY(id)
) DEFAULT CHARACTER SET UTF8;

-- 사용자
CREATE TABLE MEMBER (
	  ID INT NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(255) NOT NULL
	, ACCOUNT VARCHAR(255) NOT NULL UNIQUE
	, PASSWORD VARCHAR(255) NOT NULL
	, AUTHORITY INT
	, LOGIN_FAIL_CNT INT
	, LAST_ACCESS_DT  DATETIME
	, REG_DATE DATETIME
	, REG_ID VARCHAR(255)
	, UPD_DATE DATETIME
	, UPD_ID VARCHAR(255)
	, PRIMARY KEY (id)
) DEFAULT CHARACTER SET UTF8;