-- 메뉴
CREATE TABLE MENU (
	  ID INT NOT NULL AUTO_INCREMENT 
	, PARENT_NUM INT 
	, DEPTH INT
	, NAME VARCHAR(100) 
	, PATH VARCHAR(100)
	, REG_DATE DATETIME
	, REG_ID VARCHAR(255)
	, UPD_DATE DATETIME
	, UPD_ID VARCHAR(255)
	, PRIMARY KEY(id)
) DEFAULT CHARACTER SET UTF8;

INSERT INTO menu(parent_num, depth, NAME, path) 
VALUES (NULL, 0, '메뉴', NULL);
COMMIT;

-- 사용자
CREATE TABLE MEMBER (
	  ID INT NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(255) NOT NULL
	, ACCOUNT VARCHAR(255) NOT NULL UNIQUE
	, PASSWORD VARCHAR(255) NOT NULL
	, AUTHORITY INT
	, LOGIN_FAIL_CNT INT
	, LAST_ACCESS_DT  DATETIME
	, REG_DATE DATETIME
	, REG_ID VARCHAR(255)
	, UPD_DATE DATETIME
	, UPD_ID VARCHAR(255)
	, PRIMARY KEY (id)
) DEFAULT CHARACTER SET UTF8;

-- 점포
CREATE TABLE Store (
	  ID INT NOT NULL AUTO_INCREMENT
	, ACCOUNT INT NOT NULL UNIQUE
	, STORE_NAME VARCHAR(255) NOT NULL
	, REPRE_NAME VARCHAR(255) NOT NULL
	, ADDRESS1 VARCHAR(255)
	, ADDRESS2 VARCHAR(255)
	, TEL VARCHAR(255)
	, OPER_TIME VARCHAR(4)
	, LIKE_CNT INT
	, ETC VARCHAR(255)
	, REG_DATE DATETIME
	, REG_ID VARCHAR(255)
	, UPD_DATE DATETIME
	, UPD_ID VARCHAR(255)
	, PRIMARY KEY (id)
	, FOREIGN KEY (ACCOUNT) REFERENCES MEMBER (ID)
) DEFAULT CHARACTER SET UTF8;