INSERT INTO Sale(STORE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO Sale(STORE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, '20230626', 10500, 3, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개 크림 1개
INSERT INTO Sale(STORE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, '20230626', 12000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 딸기 2개
INSERT INTO Sale(STORE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO Sale(STORE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, '20230626', 13500, 3, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개 커피 1개

INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 37, 4, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 37, 5, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 38, 6, '20230626', 12000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 딸기 2개
INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 37, 7, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 37, 8, '20230626', 10000, 2, SYSDATE(), NULL, SYSDATE(), NULL); -- 누텔라 2개
INSERT INTO SaleItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 40, 8, '20230626', 3500, 1, SYSDATE(), NULL, SYSDATE(), NULL); -- 커피 1개

INSERT INTO SalePlusItem(STORE_ID, ITEM_ID, SALE_ID, SALE_DATE, AMT, QTY, REG_DATE, REG_ID, UPD_DATE, UPD_ID) 
VALUES(8, 17, 5, '20230626', 500, 1, SYSDATE(), NULL, SYSDATE(), NULL); -- 크림 1개

SELECT * FROM store

INSERT INTO storeOpen(store_id, open_yn, REG_DATE, REG_ID, UPD_DATE, UPD_ID) values(8, 1, SYSDATE(), NULL, SYSDATE(), NULL);
INSERT INTO storeOpen(store_id, open_yn, REG_DATE, REG_ID, UPD_DATE, UPD_ID) values(14, 1, SYSDATE(), NULL, SYSDATE(), NULL);
